project:
  type: website
  output-dir: docs

website:
  title: "A practical guide to SAE"
  sidebar:
    style: "docked"     # left, always visible
    search: true
    collapse-level: 1   # collapse deeper levels by default
    contents:
      - about.qmd
      - href: index.qmd
        text: Introduction
      - section: "Introduction"
        contents:
          - introduction/index.qmd     # section landing page
          - introduction/sub1.qmd      # subsection link 1
          - introduction/sub2.qmd      # subsection link 2


format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    css: styles.css


bibliography: ref.bib   # <--- point to your bib file
csl: apa.csl


